apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dotnet-core-web-api
  name: dotnet-core-web-api
spec:
  containers:
  - image: dmakeroam/webapp:1.0.1
    name: dotnet-core-web-api
    resources: {}
    env: 
    - name: ASPNETCORE_URLS
      value: "http://*:8090"
    - name: ASPNETCORE_ENVIRONMENT
      value: "Production"
    livenessProbe:
      httpGet:
        path: /health
        port: 8090
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health
        port: 8090
        scheme: HTTP    
      initialDelaySeconds: 10
      periodSeconds: 10      
    ports:
    - containerPort: 8090
    volumeMounts:
    - name: appvolume
      mountPath: "/app/appsettings.Production.json"
      subPath: "appsettings.Production.json"
    imagePullPolicy: Always
  volumes:
  - name: appvolume
    configMap:
      name: appsettings
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}